sonar.projectKey=foodgram
sonar.sources=backend,frontend/src
sonar.exclusions=**/migrations/**,**/node_modules/**,**/venv/**,**/build/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
