apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodgram-db
  namespace: foodgram
  labels:
    app: foodgram-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodgram-db
  template:
    metadata:
      labels:
        app: foodgram-db
    spec:
      containers:
      - name: postgres
        image: postgres:13.0-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: foodgram-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: foodgram-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: foodgram-secrets
              key: DB_NAME
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: foodgram-db
  namespace: foodgram
  labels:
    app: foodgram-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: foodgram-db
  type: ClusterIP
